version: '2'
services:
  eurekaserver:
   image:  wociechf/eurekaserver:tutoro
   ports:
       - "8761:8761"
  configserver:
    image: wociechf/configserver:tutoro
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"
  zipkin:
    image: wociechf/zipkinserver:tutoro
    ports:
      - "9411:9411"
    environment:
      SERVER_PORT: "9411"
  zuulserver:
    image: wociechf/zuulserver:tutoro
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://zipkin:9411"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZIPKIN_PORT:         "9411"
  database1:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tutoro
      POSTGRES_PASSWORD: tutor
      POSTGRES_DB: tutor
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql/tutor

  database2:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tutoro
      POSTGRES_PASSWORD: tutor
      POSTGRES_DB: tutoro_relations
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql/tutoro_relations

  tutoroservice:
    image: wociechf/tutoro:tutoro
    ports:
      - "8090:8090"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8090"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://zipkin:9411"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
      ZIPKIN_PORT:         "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
  #Attention:  Replace the value in the “command” attribute with the value supplied to you from Papertrail
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs6.papertrailapp.com:36814
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  neo4j:
    image: neo4j:3.0
    ports:
      - "17474:7474"
      - "17687:7687"
    volumes:                  ## adds folder with login/password
      - ./db/dbms:/data/dbms

  graph-relation-service:
      image: wociechf/graph-relation-service:tutoro
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        ZIPKIN_URI: "http://zipkin:9411"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
        DATABASESERVER_PORT: "5432"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        ZUULSERVER_PORT:     "5555"
        KAFKASERVER_PORT:    "2181"
        REDIS_PORT:          "6379"
        ZIPKIN_PORT:         "9411"
        ENCRYPT_KEY:       "IMSYMMETRIC"