server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://gitlab.com/wojtasfi/tutoro-config.git
          searchPaths: zuulservice, tutoroservice, graph-relation-service, authentication-service, recommendation-service
          username: wojtasfi
          password: POLlop123

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
